In [19]:
import sys
import cv2
import numpy as np
import matplotlib.pyplot as plt

from models import multiscale_model as multiscale
from models import model
from models import track_model
from src.utils import visualize_detection_video, visualize_tracking_video, visualize_detection_image

In [20]:
model_path = "checkpoints/rgb.pt"
video_path = "data/RGB_video/videos/test/BIRD_00160.mp4"

In [ ]:
multiscale_model = multiscale.DetectionModel(
                                    model_path,
                                    conf_threshold=0.2,
                                    iou_threshold=0.1,
                                    device="cuda",
                                    )

yolo_model = model.DetectionModel(
                                    model_path,
                                    conf_threshold=0.2,
                                    iou_threshold=0.1,
                                    device="cuda",
                                    )


In [22]:
multiscale_det_outputs = multiscale_model.video_detect(video_path)
yolo_det_outputs = yolo_model.video_detect(video_path)


In [23]:
multiscale_det_outputs

[{'boxes': [[np.float64(159.37639236450195),
    np.float64(35.778385162353516),
    np.float64(172.43219375610352),
    np.float64(48.530860900878906)]],
  'scores': [np.float64(0.6047745401209051)],
  'labels': [np.float64(0.0)]},
 {'boxes': [[np.float64(161.14091873168945),
    np.float64(38.662776947021484),
    np.float64(173.58623504638672),
    np.float64(50.93451690673828)]],
  'scores': [np.float64(0.498622076851981)],
  'labels': [np.float64(0.0)]},
 {'boxes': [[np.float64(161.76267623901367),
    np.float64(39.43098449707031),
    np.float64(174.38508987426758),
    np.float64(52.057525634765625)]],
  'scores': [np.float64(0.48801502314480866)],
  'labels': [np.float64(0.0)]},
 {'boxes': [[np.float32(161.76268),
    np.float32(39.430984),
    np.float32(174.3851),
    np.float32(52.057526)]],
  'scores': [np.float64(0.3590542062123616)],
  'labels': [np.float64(0.0)]},
 {'boxes': [[np.float32(161.76268),
    np.float32(39.430984),
    np.float32(174.3851),
    np.float32(52.

In [24]:
yolo_det_outputs

[{'boxes': [tensor([160.3661,  35.1292, 172.9846,  48.8931])],
  'scores': [tensor(0.7324)],
  'labels': [tensor(0.)]},
 {'boxes': [tensor([162.1273,  37.8011, 174.3474,  50.8598])],
  'scores': [tensor(0.7778)],
  'labels': [tensor(0.)]},
 {'boxes': [tensor([162.3433,  39.2072, 174.9244,  52.4306]),
   tensor([230.1480,  72.4114, 243.0023,  84.2671]),
   tensor([232.3701,  56.6781, 245.0343,  68.8608])],
  'scores': [tensor(0.6864), tensor(0.4625), tensor(0.2597)],
  'labels': [tensor(0.), tensor(0.), tensor(0.)]},
 {'boxes': [tensor([ 96.2932,  77.0725, 108.4794,  88.4342])],
  'scores': [tensor(0.3718)],
  'labels': [tensor(0.)]},
 {'boxes': [tensor([170.0960,  43.8271, 182.4247,  56.6809])],
  'scores': [tensor(0.4471)],
  'labels': [tensor(0.)]},
 {'boxes': [], 'scores': [], 'labels': []},
 {'boxes': [tensor([168.3134,  45.4106, 179.8515,  57.2254]),
   tensor([217.0130,  58.4493, 229.8458,  71.2628])],
  'scores': [tensor(0.2569), tensor(0.2218)],
  'labels': [tensor(0.), tensor(

In [25]:
visualize_detection_video(video_path, multiscale_det_outputs, output_path="outputs/demo/RGB/multiscale_BIRD_00160.mp4")
visualize_detection_video(video_path, yolo_det_outputs, output_path="outputs/demo/RGB/yolo_BIRD_00160.mp4")
